#ifndef CARD_H
#define CARD_H

// This file defines the Card type used to represent playing cards.
// It also includes some useful constants and operators.
// Do not edit this file.

#include <iostream>

enum Rank {
  TWO   =  2,
  THREE =  3,
  FOUR  =  4,
  FIVE  =  5,
  SIX   =  6,
  SEVEN =  7,
  EIGHT =  8,
  NINE  =  9,
  TEN   = 10,
  JACK  = 11,
  QUEEN = 12,
  KING  = 13,
  ACE   = 14
};

enum Suit {
  CLUBS    = 0,
  DIAMONDS = 1,
  HEARTS   = 2,
  SPADES   = 3
};


struct Card {
  // Member Variables
  Rank rank;
  Suit suit;

  // Default Constructor
  // This creates a "Zero of Clubs"
  Card() {
    rank = Rank(0);
    suit = Suit(0);
  }

  // User-Friendly Constructor 1
  Card(int rank, Suit suit) {
    this->rank = Rank(rank);
    this->suit = suit;
  }

  // User-Friendly Constructor 2
  Card(Rank rank, Suit suit) {
    this->rank = rank;
    this->suit = suit;
  }

  // A full set of comparison operators.
  bool operator <  (Card other) const {return rank <  other.rank || (rank == other.rank && suit <  other.suit);}
  bool operator <= (Card other) const {return rank <  other.rank || (rank == other.rank && suit <= other.suit);}
  bool operator >  (Card other) const {return rank >  other.rank || (rank == other.rank && suit >  other.suit);}
  bool operator >= (Card other) const {return rank >  other.rank || (rank == other.rank && suit >= other.suit);}
  bool operator == (Card other) const {return rank == other.rank && suit == other.suit;}
  bool operator != (Card other) const {return rank != other.rank || suit != other.suit;}

  // Fun with Unicode characters...
  void print() const {
    if(rank >= Rank::JACK && rank <= Rank::ACE) {
      std::cout << "JQKA"[rank - Rank::JACK];
    }
    else if(rank >= 0 && rank <= 10) {
      std::cout << rank;
    }
    else {
      std::cout << 'X';
    }

    const static char* SUITS[] = {"♣", "♦", "♥", "♠"};
    if(suit >= Suit::CLUBS && suit <= Suit::SPADES) {
      std::cout << SUITS[suit];
    }
    else {
      std::cout << '?';
    }
  }
};


struct Node {
  // Member Variables
  Card  card;
  Node* next;

  // Default Constructor
  Node() {
    // Leave it all uninitialized...
  }

  // User-Friendly Constructor
  Node(Card card, Node* next) {
    this->card = card;
    this->next = next;
  }
};

#endif
